export const MOCK_WEBTOONS = [
  {
    id: '1',
    title: '여신강림',
    genre: '로맨스',
    emotion: '설렘',
    image: 'https://via.placeholder.com/300x400?text=여신강림',
    curator: '@manga_sommelier',
    description: '평범한 여고생의 변신 이야기',
    comment: '외모 콤플렉스를 가진 주인공이 새로운 학교에서 메이크업으로 자신감을 찾아가는 이야기예요. 단순 로맨스가 아니라 성장과 설렘이 함께 와요. 캐릭터 간 케미가 좋아서 읽다 보면 웃고, 설레고, 주인공을 응원하게 돼요.',
  },
  {
    id: '2',
    title: '신의 탑',
    genre: '판타지',
    emotion: '자극',
    image: 'https://via.placeholder.com/300x400?text=신의탑',
    curator: '@webtoon_lover',
    description: '탑을 올라가는 소년의 모험',
    comment: '탑을 오르는 여정 속에서 생존, 배신, 동료애가 계속 뒤섞여요. 세계관이 탄탄하고 속도감 있는 전개 덕분에 한 화만 더가 아니라 한 시즌 더가 되는 작품이에요. 판타지 웹툰 좋아한다면 한번은 꼭 경험해야 해요.',
  },
  {
    id: '3',
    title: '일상',
    genre: '일상',
    emotion: '위로',
    image: 'https://via.placeholder.com/300x400?text=일상',
    curator: '@comfort_reader',
    description: '따뜻한 일상의 순간들',
    comment: '크게 사건이 일어나지 않아요. 그저 평범한 하루와 사람들 이야기인데, 그게 묘하게 따뜻해요. 빠르게 흘러가는 일상 속 멈춤 같은 순간을 주는 웹툰이라 지친 날 읽기 좋아요.',
  },
  {
    id: '4',
    title: '내 사위의 여자',
    genre: '드라마',
    emotion: '여운',
    image: 'https://via.placeholder.com/300x400?text=내사위의여자',
    curator: '@drama_enthusiast',
    description: '복잡한 가족관계 이야기',
    comment: '가족, 관계, 선택에 대한 이야기예요. 단순한 드라마가 아니라 내가였다면? 하고 생각하게 만드는 서사 구조가 강점이에요. 읽고 나면 마음에 오래 남아요.',
  },
  {
    id: '5',
    title: '쌍갑빙고',
    genre: '코미디',
    emotion: '웃음',
    image: 'https://via.placeholder.com/300x400?text=쌍갑빙고',
    curator: '@comedy_fan',
    description: '웃음이 나오는 일상 만화',
    comment: '회사 현실 풍자와 과장된 캐릭터들이 계속 상황 코미디를 만들어내요. 잔잔하게 웃는 게 아니라 터져 나오는 웃음이에요. 스트레스 해소용으로 완벽해요.',
  },
  {
    id: '6',
    title: '순정만화 같은 그 뭔가',
    genre: '로맨스',
    emotion: '설렘',
    image: 'https://via.placeholder.com/300x400?text=순정만화',
    curator: '@romance_expert',
    description: '두 남녀의 어색한 로맨스',
    comment: '우연한 만남, 서툰 감정, 어색한 거리감… 전형적인 로맨스 전개지만 연출이 섬세해요. 첫사랑 감정을 정확히 건드리는 웹툰이라 심장이 간질간질해져요.',
  },
  {
    id: '7',
    title: '계약연인',
    genre: '로맨스',
    emotion: '설렘',
    image: 'https://via.placeholder.com/300x400?text=계약연인',
    curator: '@manga_sommelier',
    description: '계약에서 시작된 사랑',
    comment: '가짜 연애로 시작해 진짜 감정이 생겨버리는 고전적 구조지만, 속도감 있는 갈등과 서사가 이 장르의 매력을 극대화해요. 케미 좋아하는 사람은 무조건 좋아할 스타일.',
  },
  {
    id: '8',
    title: '시간을 달리는 소녀',
    genre: '판타지',
    emotion: '자극',
    image: 'https://via.placeholder.com/300x400?text=시간달리는',
    curator: '@webtoon_lover',
    description: '시간 여행의 신비로운 모험',
    comment: '시간을 넘나들며 선택과 후회를 반복하는 이야기예요. 판타지인데 감정선이 섬세해서 서사 몰입도가 높아요. 읽다 보면 어느새 다음 화를 누르고 있어요.',
  },
  {
    id: '9',
    title: '용의 중심',
    genre: '판타지',
    emotion: '자극',
    image: 'https://via.placeholder.com/300x400?text=용의중심',
    curator: '@fantasy_fan',
    description: '위대한 전투의 서막',
    comment: '세계관이 크고 전투 장면과 성장 서사가 계속 이어져요. 초반 세계관 적응만 지나면 진짜 몰입돼요. 장르판타지 좋아하는 사람이라면 빠질 수밖에 없어요.',
  },
  {
    id: '10',
    title: '고양이를 빌려드립니다',
    genre: '일상',
    emotion: '위로',
    image: 'https://via.placeholder.com/300x400?text=고양이',
    curator: '@comfort_reader',
    description: '고양이와 함께하는 일상',
    comment: '일상 속 작은 슬픔과 외로움을 고양이라는 매개체로 따뜻하게 감싸줘요. 읽는 동안 마음이 천천히 풀어지는 느낌이 들어요. 조용한 위로가 필요할 때 추천해요.',
  },
  {
    id: '11',
    title: '미안하다 사랑한다',
    genre: '드라마',
    emotion: '위로',
    image: 'https://via.placeholder.com/300x400?text=미안하다',
    curator: '@daily_lover',
    description: '복잡한 감정의 이야기',
    comment: '사랑하지만 다가갈 수 없는 감정과 상처를 다루는 이야기예요. 감정을 숨기지 않고 정면으로 그려서 공감하고 울고 치유받는 경험을 줘요.',
  },
  {
    id: '12',
    title: '고백',
    genre: '드라마',
    emotion: '여운',
    image: 'https://via.placeholder.com/300x400?text=고백',
    curator: '@drama_enthusiast',
    description: '일상 속 숨겨진 이야기',
    comment: '사랑, 진실, 선택의 무게를 다루는 작품이에요. 결말에 가까워질수록 감정이 깊어지고 문장이 오래 남아요. 생각할 거리 많은 웹툰 좋아한다면 추천.',
  },
  {
    id: '13',
    title: '청춘블루스',
    genre: '드라마',
    emotion: '여운',
    image: 'https://via.placeholder.com/300x400?text=청춘',
    curator: '@drama_fan',
    description: '인생에 대한 깊은 성찰',
    comment: '청춘의 불안, 실패, 성장이라는 묵직한 주제를 감각적으로 표현한 작품이에요. 우울한데 위로돼요. 지금의 나를 돌아보게 만드는 힘이 있어요.',
  },
  {
    id: '14',
    title: '빈센조',
    genre: '코미디',
    emotion: '웃음',
    image: 'https://via.placeholder.com/300x400?text=빈센조',
    curator: '@comedy_fan',
    description: '터질 듯한 웃음이 가득',
    comment: '진지한 상황에 엉뚱한 요소를 섞어서 웃음을 만들어내요. 캐릭터 개성이 강해서 한 번 빠지면 계속 따라가게 되는 매력이 있어요.',
  },
  {
    id: '15',
    title: '헬로우 기사',
    genre: '코미디',
    emotion: '웃음',
    image: 'https://via.placeholder.com/300x400?text=기사',
    curator: '@comedy_master',
    description: '기사의 엉뚱한 일상',
    comment: '상황과 대사 타이밍이 뛰어나서 자연스럽게 웃음이 나요. 가볍게 읽기 좋고, 머리 쓰지 않고 웃고 싶을 때 딱이에요.',
  },
];

export const MOCK_CURATORS = [
  {
    id: '1',
    nickname: 'manga_sommelier',
    level: 'Expert',
    badge: '🍷',
    followers: 1240,
    emotion: '위로',
  },
  {
    id: '2',
    nickname: 'webtoon_lover',
    level: 'Pro',
    badge: '📚',
    followers: 890,
    emotion: '자극',
  },
  {
    id: '3',
    nickname: 'comfort_reader',
    level: 'Master',
    badge: '☕',
    followers: 2150,
    emotion: '설렘',
  },
];
